# Generated by Django 5.1.7 on 2025-03-15 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_lawyer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Client', 'Client'), ('Lawyer', 'Lawyer')], default='Client', max_length=10),
        ),
    ]
