# Generated by Django 5.1.7 on 2025-03-15 23:39

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    clients_group, _ = Group.objects.get_or_create(name='Client')
    lawyers_group, _ = Group.objects.get_or_create(name='Lawyer')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_is_lawyer_customuser_role'),
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
