# Generated by Django 5.1.7 on 2025-03-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                max_length=10,
                choices=[
                    ("Client", "Client"),
                    ("Lawyer", "Lawyer"),
                    ("Admin", "Admin"),
                ],
                default="Client",
            ),
        ),
    ]
