services:
  db:
    image: postgres:17.4
    env_file:
      - .env
    ports:
      - "5432:5432"

  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["python", "manage.py", "test", "--parallel"]