# Generated by Django 5.1.7 on 2025-03-12 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('practice_area', models.CharField(choices=[('civil', 'Civil Law'), ('criminal', 'Criminal Law'), ('corporate', 'Corporate Law'), ('administrative', 'Administrative Law')], max_length=20)),
                ('bio', models.TextField()),
                ('available_from', models.TimeField()),
                ('available_to', models.TimeField()),
            ],
        ),
    ]
