# Generated by Django 5.1.7 on 2025-03-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0002_unavailabletimeslot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyerprofile',
            name='bio',
        ),
    ]
