# Generated by Django 5.1.7 on 2025-03-16 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0003_remove_lawyerprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='available_from',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='available_to',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
    ]
