name: CI/CD with Docker and Render

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Create .env file for CI/CD
        run: |
          printf "DJANGO_SECRET_KEY=%s\n" "${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          printf "DATABASE_URL=%s\n" "${{ secrets.DATABASE_URL }}" >> .env
          printf "POSTGRES_USER=%s\n" "${{ secrets.POSTGRES_USER }}" >> .env
          printf "POSTGRES_PASSWORD=%s\n" "${{ secrets.POSTGRES_PASSWORD }}" >> .env
          printf "POSTGRES_DB=%s\n" "${{ secrets.POSTGRES_DB }}" >> .env

      - name: Run Django tests with Docker Compose
        run: docker compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from web

      - name: Clean up Docker Compose
        run: docker-compose -f docker-compose.test.yml down

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
